### ISSUE TITLE
DVD sector size on KREON drives

### ISSUE THREAD

**Issue by superg** [superg/redumper#100]
Is incorrectly reported if using SCSI READ_CAPACITY
Prioritize size calculation from DVD physical structures, if structures are not reported (some lame drives), fallback to READ_CAPACITY.

**Comment by mnadareski** [comment]
According to claunia, the value being returned is not the equivalent of -1. The value is the equivalent of -16973820

**Comment by mnadareski** [comment]
Another tidbit that may help: "being a normal DVD maybe the Kreon is trying to read the second PFI from, well, a normal DVD block with normal data"

**Comment by superg** [comment]
Good to know, it's close to 24-bit signed integer and internally 24-bit value is using to report the structure size (might be related):
https://github.com/superg/redumper/blob/main/dvd/dvd_dump.ixx#L160
