### ISSUE TITLE
Readme is currently very CD-orientated

### ISSUE THREAD

**Issue by JohnVeness** [superg/redumper#106]
Hi, many thanks for this project.

Currently, the README is almost entirely written as if the program is only for CDs, in the drive types sections for example. Can information about DVD and BD drives and dumping commands be added?

**Comment by superg** [comment]
Hi John,
Yes you're very correct, redumper started as CD centric dumper and other functionality was added later. CD is very complicated when you take into account read/write offset, lead-in/lead-out, mastering issues and a lot of other things.
I will have to update the documentation at some point but overall other media "just" works. If you want to dump DVD/HD-DVD/Blu-ray media, it's enough to run `redumper` without any options for the most scenarios.

Usually, the primary redumper user base are members of redump.org. If you happen to come from the outside, I'd suggest to look into MPF (https://github.com/SabreTools/MPF) that is basically a frontend for redumper that knows default settings depending on a disc type etc.

**Comment by JohnVeness** [comment]
Thanks for the quick reply :). I'm already a dumper on redump.org and am familiar with MPF, although I'm trying to move to using Linux for dumping so cannot use MPF on that.

Indeed, simply running "redumper" seems to work great for DVDROMs I've tried. :)

**Comment by superg** [comment]
I did some README changes, hopefully more clear now.

**Comment by JohnVeness** [comment]
Thank you!
