### ISSUE TITLE
[Feature Request] Command-line option to enable CD-TEXT dumping on 4824 drives

### ISSUE THREAD

**Issue by HeroponRikiBestest** [superg/redumper#115]
Self explanatory. My 4824 doesn't crash when trying to read multisession cd-text, so it would be nice to be able to re-enable it.

**Comment by HeroponRikiBestest** [comment]
Finally found a multisession disc with CD-TEXT to confirm with; attached are logs from dumping on my 4824 via build 98 with CD-TEXT included. For whatever reason, my 4824 can definitely read it just fine.
[engineLogs.zip](https://github.com/superg/redumper/files/14156274/engineLogs.zip)

**Comment by superg** [comment]
It might be disc dependent. Anyways I'll have an option for enabling it.

**Comment by HeroponRikiBestest** [comment]
Fixed via https://github.com/superg/redumper/pull/169
