### ISSUE TITLE
Discrepancy between DiscImageCreator and redumper for SecuROM 4 disc

### ISSUE THREAD

**Issue by maxz** [superg/redumper#117]
Recently I began dumping my discs with both DiscImageCreator and redumper.

On the disc for Empire Earth, I discovered a discrepancy regarding the errors.
More specifically regarding a single mode 1 sector among the mode 2 sectors. Both tools detect that correctly.
But the [redump.org](http://redump.org/disc/47968/) entry and DiscImageCreator state it as an error and redumper does not.

So what is the case here? Is it an oversight in redumper? Or will the redump.org policy going forward be to not record these sectors as erroneous anymore?

Logs: https://archive.org/download/redump.org-logs/EEARTH.zip

DiscImageCreator's `EEARTH.img_EccEdc.txt`:
```
[ERROR] Number of sector(s) where mode is invalid: 1
        Sector: 290471, 
Total errors: 1
Total warnings: 0
```
Redumper's `EEARTH.log`:
```
CD-ROM [EEARTH.bin]:
  sectors count: 290475
  mode1 sectors: 1
  mode2 (form 1) sectors: 290474

  REDUMP.ORG errors: 0
```

**Comment by maxz** [comment]
Ok, it certainly makes sense to view it this way. My exact verdict would depend on the format's specification.

It still leaves me non the wiser what the correct error count for submissions would be in this case, especially since the redump submission form still states `Errors count (edccchk v1.26)` and therefor specifically refers to that point of view.
I guess I will try using the redumper error count as basis for my submissions and then go by the moderator response.

Do you maybe have a link to the discussion on the forum? I tried finding it but could not.
Did it come to any conclusion regarding which of the viewpoints to prefer for submissions?

**Comment by superg** [comment]
That was discussed privately and there is no 100% consensus at this point. Submit with either error count and hopefully moderator will bring this up again.
