### ISSUE TITLE
Missing Plextor Drive PX-750A

### ISSUE THREAD

**Issue by Citrodata** [superg/redumper#131]
It works with the settings of the PX-755A I own one and can give more information if needed.

**Comment by superg** [comment]
Can you do a full dump of a CD with data and audio tracks and post a log here?

**Comment by Citrodata** [comment]
Sorry, I wrote the Wrong drive, I meant the PX-740a. Read in forums that the PX-750a is not a real plextor sadly.
[PX716a.log](https://github.com/superg/redumper/files/14759589/PX716a.log)
[PX750a.log](https://github.com/superg/redumper/files/14759590/PX750a.log)
I have more other drives if your interested but I'm still sorry to bother you.

**Comment by Citrodata** [comment]
I also have 2 LG Drives
[WH16NS40.log](https://github.com/superg/redumper/files/14760325/WH16NS40.log)
[GDR-8164B.log](https://github.com/superg/redumper/files/14760326/GDR-8164B.log)

The WH16NS40 should be 4MB cache.

**Comment by superg** [comment]
I don't think I understand what do you mean here.
You ask about PX-750A, then you say you meant PX-740A but add a log of PX-750A. 

In any way, the log of your 750 shows that 750 is a bad drive. So is 740, it's known to be bad and I own it.
It can be used with redumper, yes - but often it will not give you 1:1 data so we don't accept it at redump.org. But if your usecases are different, of course you can use redumper with your drives.

WH16NS40 cache - how do you know it's 4Mb? In log you used GENERIC drive so we don't even know if it has cache reading opcode.

**Comment by Citrodata** [comment]
Im Sorry for the confusion i caused
The PX-750a I own is, from what i can get from the internet, just a little better PX-740a but not a real Plextor.
With the WH16NS40 i used both 3MB and 8MB but both din't work. And after Googling a little bit i got from the Internet that it is 4MB.

**Comment by superg** [comment]
If neither has worked and there is no message that cache was read - this drive doesn't have cache read opcode at all. 4Mb or not is not important if cache is not accessible.
