### ISSUE TITLE
Redump.org Errors

### ISSUE THREAD

**Issue by Citrodata** [superg/redumper#132]
While Ripping the Game Heavy Metal I got this error message back.
`REDUMP.ORG errors: 582`
[Heavy Metal Fakk 2.log](https://github.com/superg/redumper/files/14764664/Heavy.Metal.Fakk.2.log)

**Comment by tjanas** [comment]
Maybe it’s a combination of SafeDisc and your disc being damaged, resulting in bad correction of some C2 errors?

Is it this disc? http://redump.org/disc/7325/

**Comment by superg** [comment]
It is SafeDisc protected, the error count is expected.
