### ISSUE TITLE
Asus SDRW-08D2S-U support?

### ISSUE THREAD

**Issue by gingerbeardman** [superg/redumper#135]
I bought a SDRW-08D2S-U but redumper is not detecting it?

https://github.com/superg/redumper/blob/1f4a560dd4dd6b704e5dcf9aa5c71aa59e2c01d0/drive.ixx#L205

**Comment by superg** [comment]
By not detecting you mean what exactly, unable to dump anything and mass errors?

**Comment by gingerbeardman** [comment]
When I run redumper it says no recognised drives are found (or something along those lines)

**Comment by superg** [comment]
Can you provide a log output?

**Comment by gingerbeardman** [comment]
Sure, but please tell me exactly how to produce the logs you need.

```
% ./redumper
error: no ready drives detected on the system
```

There is a disc in the drive (I've tried with it mounted and unmounted)

**Comment by superg** [comment]
So that has nothing to do with not detecting the drive, basically something holds the drive and redumper doesn't see it.
Which OS do you use, is it Windows?

**Comment by gingerbeardman** [comment]
No, I'm on macOS. I will see what could be holding the drive.

I tried in Windows 11 ARM VMware and the drive is recognised and dumping begins.

```
PS C:\Users\matt\Desktop\redumper-2024.04.07_build317-win64\bin> ./redumper.exe
warning: drive read offset not found in the database
redumper v2024.04.07 build_317 [Apr  7 2024, 19:05:43]

drive path: D:
drive: ASUS - SDRW-08D2S-U (revision level: BA01, vendor specific: 2019/06/21 12:53)
drive configuration: GENERIC (read offset: +0, C2 shift: 0, pre-gap start: +0, read method: BE, sector order: DATA_C2_SUB)
drive read speed: <optimal>

current profile: CD-ROM

image path: .
image name: dump_240407_215355_D

*** DUMP

disc TOC:
  track 1 {  data }
    index 01 { LBA:      0, MSF: 00:02:00 }
  track A {  data }
    index 01 { LBA: 134983, MSF: 30:01:58 }

warning: unsupported drive read method
warning: unable to read CD-TEXT, SCSI (SC: CHECK CONDITION, SK: ILLEGAL REQUEST, ASC: INVALID FIELD IN CDB)
/ [  2%] LBA:   2777/134983, errors: { SCSI: 0, C2: 2778, Q: 2778 }
```

Regarding "warning: drive read offset not found in the database" I read at http://www.accuraterip.com/driveoffsets.htm that this drive has been purged from recommendation

**Comment by superg** [comment]
Did you unmount the drive?
There are steps in readme on how to do it.

**Comment by gingerbeardman** [comment]
Yes, indeed, I did unmount the drive on macOS.

**Comment by gingerbeardman** [comment]
here's a screenshot

<img width="714" alt="image" src="https://github.com/superg/redumper/assets/49612/908ca81c-82b8-45db-b404-7fd3eb821655">

**Comment by gingerbeardman** [comment]
I notice with this drive it's not possible to dump mixed mode discs, even on Windows?

**Comment by superg** [comment]
Let's solve one issue at a time.
I've just realized you didn't provide --drive argument to redumper. Execute `diskutil list` and provide this argument like it is described in https://github.com/superg/redumper/blob/main/README.md#macos

**Comment by gingerbeardman** [comment]
```
% ./redumper --drive=disk5
error: failed to create service plugin interface, MACH ((iokit/common) resource shortage)
```

I also just read in the readme that I shouldn't have bought this drive, so feel free to close and I will buy a more supported one.

**Comment by superg** [comment]
If you read https://github.com/superg/redumper/blob/main/README.md#macos until the end - there is an answer, just copy binary to /usr/local/bin and it will work. It's irrelevant of the drive, it will happen even with plextor or asus. Mac is full of undocumented surprises.
