### ISSUE TITLE
DVD-9 with "READ_CAPACITY / PHYSICAL sectors count mismatch" warning dumps only half of actual sectors

### ISSUE THREAD

**Issue by noigeaR** [superg/redumper#142]
Dumping the two DVD-9 discs http://redump.org/disc/66115/ and http://redump.org/disc/66116/ results in dumps, that are exactly half the size they should be.
3515187200 instead of 7030374400 for Disc 1 and 2857467904 instead of 5714935808 for Disc 2.

Logs contain `warning: READ_CAPACITY / PHYSICAL sectors count mismatch, using PHYSICAL`

Disc 1 logs for build 311 on Asus BW-16D1HT and build 321 on Asus SDRW-08D2S-U
[Shogun2 Disc 1_redumper311_BW-16D1HT_logs.zip](https://github.com/superg/redumper/files/15192333/Shogun2.Disc.1_redumper311_BW-16D1HT_logs.zip)
[Shogun2 Disc 1_redumper321_Asus-SDRW_logs.zip](https://github.com/superg/redumper/files/15192334/Shogun2.Disc.1_redumper321_Asus-SDRW_logs.zip)
Disc 2 log for build 311 on Asus BW-16D1HT
[Shogun2 Disc 2_redumper311_BW-16D1HT_logs.zip](https://github.com/superg/redumper/files/15192385/Shogun2.Disc.2_redumper311_BW-16D1HT_logs.zip)

Log for a disc 1 dump with DIC, which results in a correct dump
[Shogun2 Disc 1_DIC_BW-16D1HT_logs.zip](https://github.com/superg/redumper/files/15192343/Shogun2.Disc.1_DIC_BW-16D1HT_logs.zip)

**Comment by mictlantecuhtle** [comment]
Just a quick note to confirm I've encountered the same issue on another Sega PC release - Total War: Rome II (SEGA-PC145-DISC1). Logs for redumper and DIC attached for info
[Rome2 Disc 1_logs.zip](https://github.com/superg/redumper/files/15193205/Rome2.Disc.1_logs.zip)
[Rome2 Disc 1_logs_dic.zip](https://github.com/superg/redumper/files/15193214/Rome2.Disc.1_logs_dic.zip)

**Comment by superg** [comment]
By the way, what DIC does?

**Comment by maxz** [comment]
I came across the same issue.
The affected disc was the DVD-9 for [The Elder Scrolls V: Skyrim](http://redump.org/disc/85794/).

The ISO which DIC produces has a size of 5267652608  octets while the ISO produces by Redumper has a size of 2633826304 octets.
Redumper gives the same warning as in the initial report: `warning: READ_CAPACITY / PHYSICAL sectors count mismatch, using PHYSICAL`

**Logs**
[SKYRIM_DE (Redumper).zip](https://archive.org/download/redump.org-logs/SKYRIM_DE%20%28Redumper%29.zip)
[SKYRIM_DE (DiscImageCreator).zip](https://archive.org/download/redump.org-logs/SKYRIM_DE%20%28DiscImageCreator%29.zip)

**Comment by superg** [comment]
Fixed.

**Comment by maxz** [comment]
I tested build 328 and can confirm that it now images my disc properly.

**Comment by superg** [comment]
@maxz thank you, I appreciate the confirmation.
The issue happened with 2 layer parallel DVD's where both layers had the exact size, I didn't have such a disc here so had to test by code simulation.
