### ISSUE TITLE
Neo Geo CD: CATALOG 1234567890123

### ISSUE THREAD

**Issue by bikerspade** [superg/redumper#143]
http://forum.redump.org/topic/55215/neogeo-cd-samurai-spirits-zankurou-musouken-samurai-shodown-iii/

Some recent redumper dumps of Neo Geo CD discs, such as the one above, are producing an MCN value of 1234567890123 in the cuesheet.
DiscImageCreator dumps are not.

Also reported here : http://forum.redump.org/post/117308/#p117308

[51985_redumper.zip](https://github.com/superg/redumper/files/15269705/51985_redumper.zip)
[51985_DIC.zip](https://github.com/superg/redumper/files/15269706/51985_DIC.zip)

**Comment by bikerspade** [comment]
Others:
http://forum.redump.org/topic/55262/addedneogeo-cd-samurai-spirits-amakusa-kourin/
http://forum.redump.org/topic/55260/addedneogeo-cd-shinsetsu-samurai-spirits-bushidou-retsuden/
http://forum.redump.org/topic/55259/addedneogeo-cd-real-bout-garou-densetsu-special/
http://forum.redump.org/topic/55258/addedneogeo-cd-rb2-the-newcomers-real-bout-garou-densetsu-2/
http://forum.redump.org/topic/55256/addedneogeo-cd-real-bout-garou-densetsu-real-bout-fatal-fury/
http://forum.redump.org/topic/55247/addedneogeo-cd-the-last-blade-2-japanese/
http://forum.redump.org/topic/55246/addedneogeo-cd-bakumatsu-roman-gekka-no-kenshi-the-last-blade/
http://forum.redump.org/topic/55244/neogeo-cd-the-king-of-fighters-99/
http://forum.redump.org/topic/55243/neogeo-cd-the-king-of-fighters-97/
http://forum.redump.org/topic/55242/neogeo-cd-the-king-of-fighters-96/
http://forum.redump.org/topic/55240/neogeo-cd-the-king-of-fighters-98-dream-match-never-ends/
http://forum.redump.org/topic/55217/neogeo-cd-art-of-fighting-ryuuko-no-ken-gaiden/

**Comment by superg** [comment]
MCN is per disc and comes from the subchannel, not from CD-TEXT:
From samurai 3:
```
[LBA:   -151, LBAQ: 134850] control: 0000, ADR: 2, 12 34 56 78 90 12 30 00 00, crc: D1EB (+) P: 0/96
```
