### ISSUE TITLE
Content of a track with partially scrambled sectors differs from DiscImageCreator

### ISSUE THREAD

**Issue by maxz** [superg/redumper#148]
The contents of the second track for [PC Action 9/99](http://redump.org/disc/92982/) differ between Redumper and DiscImageCreator.
The first 75 sectors of that track are scrambled.

DIC seems to treat it as an audio track but descrambles the first 75 sectors.
Redumper seems to treat it as a data track.

All other tracks match.

I'm not sure what the right behaviour would be and which of the two programs would therefore have to be adjusted.
The state of affairs in the redump.org database is the result that DIC comes to.

**Logs**
[PCABONUS0999 (DiscImageCreator).zip](https://archive.org/download/redump.org-logs/PCABONUS0999%20%28DiscImageCreator%29.zip)
[PCABONUS0999 (Redumper).zip](https://archive.org/download/redump.org-logs/PCABONUS0999%20%28Redumper%29.zip)

**Comment by superg** [comment]
Please no DIC vs redumper descramble reports, redumper can't fix DIC. 
Historically DIC was inconsistent with descrambling and now redumper just detects all these issues, I will not be wasting my time on it, not anymore.

**Comment by maxz** [comment]
With build 314 of Redumper, both still came to the same result. Are you certain that this is not a regression? If everything is fine to your knowledge, then I won't bother you further about this issue.

See the log for Redumper build 314 and DIC 20240101T000844: [PC Action 1999-09 (Bonus-CD).zip](https://archive.org/download/redump.org-logs/PC%20Action%201999-09%20%28Bonus-CD%29.zip)

**Comment by superg** [comment]
I've just downloaded build_314 and build_328 archives that you shared, compared redumper logs and I see the same hashes e.g. no regression, am I missing something?

**Comment by maxz** [comment]
No, you are correct. Sorry for opening this issue.

It actually is a regression in DiscImageCreator and I somehow mixed the hashes up when comparing them.

I don't have the original DIC hashes around anymore, but since I compare all the hashes between Aaru, DiscImageCreator and Redumper programmatically and only copy the files to the submission directory if the hashes match, it has to have matched back when I dumped the disc with those versions.
