### ISSUE TITLE
Getting error when creating SKELETON

### ISSUE THREAD

**Issue by MoriGM** [superg/redumper#167]
After the ripping is finished, I get this error.

*** SKELETON (time check: 4s)

error: string is not an integer number (

Full Log 
[Der Ring Des Nibelungen.zip](https://github.com/user-attachments/files/15757417/Der.Ring.Des.Nibelungen.zip) Asus Drive
I checked it with a PX-716A and PX-755A too, but it's always the same error.

**Comment by nvllsvm** [comment]
Dupe of https://github.com/superg/redumper/issues/149

**Comment by superg** [comment]
The error can be disregarded for now as the dump files are valid, just the skeleton failed to create.
It's most likely incompliant iso9660 filename, I will look into it eventually.
