### ISSUE TITLE
Unchecked sessions leads to SEGFAULT

### ISSUE THREAD

**Issue by malespiaut** [superg/redumper#17]
Hello,

I've tried to dump a simple disc with what seems to be an unsupported drive 
```
drive: HL-DT-ST - DVD+-RW GT10N (revision level: A105, vendor specific: 09/03/31 R2 PL02)
drive configuration: GENERIC (read offset: +102, C2 shift: 0, pre-gap start: +0, read method: BE, sector order: DATA_C2_SUB)
```

After dumping the disc, `redumper` SEGFAULT. Checking in GDB reveals that [line 114 of `toc.cc`](https://github.com/superg/redumper/blob/bd045c6ee21848e067d70e1364bb4666592f8486/toc.cc#L114) is the culprit:
```C
uint32_t pregap_count = sessions.front().tracks.front().lba_start - MSF_LBA_SHIFT;
```

No code handles when `sessions` is equal to `0x0`.

**Comment by superg** [comment]
Hi,
Thanks for the report, it looks like sessions vector is empty here. 
The code in question builds TOC from the subchannel data, if it doesn't extract at least one track, it will lead to this situation.
My hunch is that drive reports that it can read subchannel data, but it reads zeroes so I try to build subchannel based TOC for essentially no data. Let me add a check there to gracefully handle the situation but overall quality of dump will be super low without subchannel information, incorrect splits, incorrect index etc.

**Comment by superg** [comment]
All right, this is corrected. The root cause here is that drive doesn't error out when subchannel data is requested but it returns zeroes in subchannel. In this case track split points are generated based on a fact that each track index0 is exactly 150 sectors.
