### ISSUE TITLE
`read_physical_structures` fails on dual layer Blu-ray discs.

### ISSUE THREAD

**Issue by Didrole** [superg/redumper#174]
Redumper fails to dump dual layer Blu-rays on my system with the following error:  
> error: failed to read disc physical structure, SCSI (SC: CHECK CONDITION, SK: ILLEGAL REQUEST, ASC: INVALID FIELD IN CDB)

After checking the source code and reading the [SCSI Multi-Media Commands - 6](http://www.13thmonkey.org/documentation/SCSI/mmc6r02g.pdf) specification document, it appears the function `cmd_read_disc_structure` is called incorrectly for multi-layer Blu-ray discs.  
According to the 6.22.3.3 section of this document the layer field is supposed to be reserved for BD discs, but the loop in `cmd_read_disc_structure` calls `cmd_read_disc_structure` for every layer of the disc whenever it's a BD or a DVD (thus violating the specs and failing when the layer number is non-zero).

**Comment by Deterous** [comment]
Solving this should also solve #153 
It does look like the changes in #5f6a2da should only occur for DVDs, but this simple fix won't be enough. Definitely on the right track.

**Comment by superg** [comment]
Let's solve one issue at a time. I will review your statements about violating the specs and reply here.

**Comment by superg** [comment]
I want to also mention that I closed PR for this.
We can reopen it anytime if it will be needed but I think this should be a simple solution.

**Comment by superg** [comment]
@Didrole, just to clarify, when redumper dumps using your drive, the call:
https://github.com/superg/redumper/blob/main/dvd/dvd_dump.ixx#L307
succeeds on the first iteration (when i == 0) but fails on the next iteration when i == 1?

**Comment by Didrole** [comment]
Yes, it's exactly the behavior I observed with my debugger.
My drive is a Lite-On iHBS112-115 2 reported as `drive: ATAPI - iHBS112 2 (revision level: PL06, vendor specific: 2012/09/17 10:50)` by redumper.

**Comment by Didrole** [comment]
Closing, as #175 has been merged.
