### ISSUE TITLE
When should I refine on incomplete pre-gap?

### ISSUE THREAD

**Issue by malvarenga123** [superg/redumper#18]
I tested dumping an audio-cd with both a Plextor Premium and a BW-16D1HT.
The ASUS dump has this warning in the log: `warning: incomplete pre-gap (session: 1, unavailable: 3/150)`
The Premium dump doesn't have it, but the dumps are identical.
Should I always use refine if the pre-gap is incomplete?

**Comment by superg** [comment]
Depend on what you're trying to ultimately achieve.

If this is redump.org submission scope, we started accepting redumper audio CD dumps using good PLEXTOR drives so you will want to dump your eligible audio cd's on your PLEXTOR before submitting them. ASUS drive dumps can be accepted a bit later after I implement some additional checks to make sure we get a good dump.

If you're asking in a more generic scope, refine use is suggested if it will improve the dump. As ASUS can't get full lead-in, it doesn't make much sense to dump on ASUS and refine on ASUS.
While it makes some sense to dump on ASUS and refine on PLEXTOR (PLEXTOR will fill in missing sectors), it's not very useful if you own both drives as you can just dump on your PLEXTOR initially.
Main refine use is if you have a disc with C2 errors as this mode combined with --retries option will incrementally fix/improve your dump and you can use different drives for that.
