### ISSUE TITLE
Request: optionally eject disc as soon as read phase is complete

### ISSUE THREAD

**Issue by Barthax** [superg/redumper#190]
Hi,

Could an option be added to redumper to eject the disc as soon as the SCSI interaction is completed, please - before Hash values, Info and Skeleton are attempted.  BD discs can take a long time for the (especially) Skeleton phase to complete and all the while the drive is unused.  I use the CLI version under Linux and I feel it would be efficient for me to be able to know I can change disc and start a new dump while the final phases of the previous disc are still completing.

Thanks for your consideration.

**Comment by Deterous** [comment]
I have code for this already. Just need to get my current PR through, then I'll open one for auto eject
