### ISSUE TITLE
[feature request] when fixing C2/SCSI errors read the sectors correctly at least twice

### ISSUE THREAD

**Issue by thegawin** [superg/redumper#196]
Some drives have bad error correction/detection.

**Comment by superg** [comment]
I will not be implementing burst mode. Redumper is using C2 for error detection, if C2 information is unreliable, you can't trust that drive. Moreover, this potential feature contradicts with sample based error correction. 
But, there is `redumper verify` implemented for DVD or later and almost finished implementation for the CD, it basically reads the whole disc and compares sectors towards what is stored in the dump, if discrepancy is found, such sector is marked as bad and it can be refined.

**Comment by thegawin** [comment]
With some scratched discs asus (JB8) has tendency to create false positives (when reading). (Way to easily, I mean on first try.)

So instead of dumping at x24 and then refine, you need to start at lowest possible speed.

**Comment by superg** [comment]
In general, ASUS is not a great drive for C2 recovery. There are more issues where cache returns same data on re-read. I suggest to stick with plextors.

**Comment by dhouck** [comment]
Two questions related to this:
1. Whatʼs the status of CD verify?  I see it isnʼt supported in `main`, but is it still almost done?
2. My drive (LG WH14NS40, but I havenʼt checked the age so donʼt know the chipset etc.) sometimes reads the same scratched disc differently, with no detected C2 errors; if I understand your comment correctly this means the drive itself is unreliable, not just the disc?  My impression was it was just that audio CDs donʼt have enough checksumming to ensure damage doesnʼt get you a different valid sector, but if itʼs a drive problem thatʼs maybe promising.  If it is the drive, will flashing a different firmware maybe fix that?

**Comment by superg** [comment]
@dhouck 
Verify command is quite supplemental, it's true that I haven't fully implemented it yet for the CD though. It can usually be substituted with fresh dump and binary comparison. 

Your drive: drive is not necessarily a problem, for scratched discs sometimes errors slip through even if no C2 for that sector is reported, it happens on all drives. Also mediatek based chipsets error correction is usually worse than good plextors (I think your drive is mediatek based). I don't think flashing it will fix any of it. Depending on what you want to do, you can either resurface the disc or get a good plextor drive (if the data is important).

**Comment by dhouck** [comment]
For this specific disc, for reasons I cannot _begin_ to guess at, aaru reads it consistently and as far as I can tell correctly.  Usually I find redumper works better, but I guess itʼs good to keep multiple options around.

In general, yeah, I think I want to get a plextor drive.

**Comment by dhouck** [comment]
Yeah, I only need verify for audio CDs.  My data CDs with issues, when they claim to have a good rip, actually do.  If it existed for all CDs Iʼd use it but audio CD is the only place where I can have a bad rip but nothing reports an error.
