### ISSUE TITLE
Plextor DVDR PX-716A on different firmware

### ISSUE THREAD

**Issue by Tatsh** [superg/redumper#23]
[`drive.cc` has it listed](https://github.com/superg/redumper/blob/main/drive.cc#L101) but with 1.11 firmware. I have 1.59 firmware. Is it really different? I have been using read method D8 and PLEXTOR mode and it seems to work fine reading extra lead-in and so forth.

**Comment by superg** [comment]
That's a really good question. So 1.59 is actually an older firmware than 1.11 :)
I had a couple drives like yours, had 1.59 and 1.5A - I think it was maybe pre-release 1.5 version so I suggest you update your firmware to 1.11.

**Comment by Tatsh** [comment]
Thanks. That was an easy fix with a Windows VM (running on USB adapter).

**Comment by Tatsh** [comment]
With the new firmware should I re-read discs that had C2 errors (and did not reach the analysis stage)? Will it make a difference? The settings (read offset, etc) are different than before.

**Comment by superg** [comment]
It's kind of recommended to always have a latest drive firmware but personally I can't tell any specific case where it actually fixed something. It's unlikely that it will fix some C2 errors.
After you updated your firmware and redumper detected the drive, C2 offset changed, yes, but it will not affect C2 quality, C2 offset is needed to properly process C2 vector overlap between sectors but it will not change the total C2 errors count.
