### ISSUE TITLE
Fast fail mode?

### ISSUE THREAD

**Issue by Tatsh** [superg/redumper#24]
I have been reading a lot of discs and it seems like > 100 C2 errors means the disc will not be recovered fully during the refine stage. Maybe an option could be added like `--maximum-c2-errors=VALUE` and this would apply to the dump and refine stages, and exit with failure when the maximum is exceeded.

**Comment by superg** [comment]
Some specific error count is not always an indicator of the disc being irrepairable.
It highly depends on a damage type. In general you never know, I have a lot of discs where it gets >1000 C2 errors and then on a second pass more than a half are corrected and eventually it's fixed. This can be implemented eventually but super low priority as I have a plenty of things to work on ATM.
Meahwhile you can use Ctrl+C anytime you think the disc is not worth refining, redumper gracefully handles interruption like this.

**Comment by Tatsh** [comment]
How is it eventually fixed for > 1000 C2 errors?

My plan is just to get the '>100 C2 error' discs to a cleaning device (like the Eco Pro2) and then try again.

**Comment by superg** [comment]
If I understand your question correctly: redumper refine command with --retries=<some number> will be re-reading those sectors and reconstruct them from samples that were read without errors.

**Comment by Tatsh** [comment]
Closing as I think this is not that common of a use case.
