### ISSUE TITLE
Add support for Hitachi-LG Data Storage drives

### ISSUE THREAD

**Issue by TorutheRedFox** [superg/redumper#28]
I've noticed that there's a Mac version of Redumper planned. As a large amount of Macs use DVD drives manufactured by Hitachi-LG Data Storage (and I'm fairly sure this applies to the external SuperDrive too), built-in support for them should be added before such a version gets released.

**Comment by superg** [comment]
Mac version requires SCSI pass through driver.
I plan to eventually implement such a driver.
Drive support is not connected to this and most likely the drives you mention lack features needed for proper scrambled mode dumping. 
Once driver will be written, you will still have to use a compatible good drive connected externally using USB or FireWire.

**Comment by TorutheRedFox** [comment]
ah

**Comment by superg** [comment]
This is already implemented in scope of generic drive support.
