### ISSUE TITLE
Bug - Redumper doesn't seem to retry C2 errors found in lead-out area?

### ISSUE THREAD

**Issue by ehw** [superg/redumper#32]
(Logs and other related files to follow once the dump is complete, if needed).

I'm currently dumping a disc in a Plextor Premium2. For some reason, the disc has a sizeable lead-out range that was discovered and dumped when using the initial CD mode. These sectors exist outside of the disc's reported TOC. During the initial read with CD mode, it marked a few sectors in this region as having C2 errors.

I reran the disc again but in refine mode with the same drive, but Redumper seems to be restricting all of the refines to within the TOC and doesn't seem to be doing anything to the errors found in the lead-out.

I know the lead-out usually doesn't contain anything...maybe. But I think this might cause issues when the dump is ready to be descrambled and split. I should be able to retry these errors if I want to...

**Comment by superg** [comment]
I specifically verified this in new refine code.
Leadout sectors (everything past TOC leadout LBA) will be refined the same way as everything else, the only limitation is that those sectors will not be displayed in the main errors: progress output, but if you enable `--verbose`, you will see detailed messages on retries.
Closing this, feel free to reopen if you find issues there.
