### ISSUE TITLE
Feature Request - Refine mode - Don't clear cache on first retry

### ISSUE THREAD

**Issue by ehw** [superg/redumper#33]
As per Sazpaimon. This was discussed with superg before, just getting it down into an issue for tracking. Discussion was mentioned here: https://discord.com/channels/410032223589236736/1022671275711270922/1065109824947372033

Not clearing cache on the first read for a given sector helps speed up refines apparently. This will also help with GD dumping too. This has been implemented by Sazpaimon in his version.

**Comment by superg** [comment]
Done in new dump code.
