### ISSUE TITLE
Feature Request: DVD support for refine and info commands

### ISSUE THREAD

**Issue by tjanas** [superg/redumper#47]
When performing a refine with a DVD that has errors, redumper will re-read the entire disc instead of just the sectors with errors.
Also, redumper currently does not support the info command on a refined DVD iso (tries to open a cuesheet that doesn't exist):
```
redumper v2023.05.21 build_152 [May 21 2023, 22:24:41]

command line: .redumper.exe info --verbose --image-name="test_dump"

*** COMMAND: info
image path: .
image name: test_dump
error: unable to open file (test_dump.cue)
```

**Comment by superg** [comment]
done
