### ISSUE TITLE
Support RibShark's hacked 3.10 firmware for ASUS/LG drives

### ISSUE THREAD

**Issue by DopefishJustin** [superg/redumper#52]
- Needs an entry in drive.cc
  - Can be worked around by passing in `--drive-type=GENERIC --drive-sector-order=DATA_C2_SUB --drive-pregap-start=-135 --drive-read-method=BE_CDDA`
- Needs some way of stopping the read once the end of the disc has been reached rather than continuing forever

**Comment by malvarenga123** [comment]
I've tried searching, but I couldn't find this firmware. Is it publicly available anywhere?

**Comment by superg** [comment]
I'd suggest to join VGPC Discord here: https://discord.gg/AHTfxQV
Folks will be able to help.

**Comment by DopefishJustin** [comment]
Fixed in c0718d8d2ccf22dea959304abc3699859d206cfa
