### ISSUE TITLE
Feature Request Track Range Filter

### ISSUE THREAD

**Issue by joshstoik1** [superg/redumper#60]
Hi there,

It would be helpful to add a track-based range filter for `dump` and `refine` operations as a more user-friendly alternative to the existing `--lba-start`/`--lba-end` and `--skip` options.

`redumper` already knows the precise track boundaries; it could save users the trouble of having to manually calculate and correctly enter that information themselves. :wink: 

**Example**

```
Track |   Start  |  Length  | Start sector | End sector
-------------------------------------------------------
    1 | 00:00.00 | 02:48.41 |            0 |      12640
    2 | 02:48.41 | 03:05.74 |        12641 |      26589
    3 | 05:54.40 | 03:34.45 |        26590 |      42684
```

If a user wanted to refine only the second track for the above audio CD, they could run either of the following:

```bash
# Current manual way.
redumper refine [drive stuff] --lba-start 12641 --lba-end 26590

# Proposed automatic way.
redumper refine [drive stuff] --tracks 2
```

**Comment by superg** [comment]
I gave it a thought and I will not be implementing this. Usually when you do advanced repair using refine you target LBA's that are bad. Advanced repair is not track based but LBA range based. There is no other scenario that I see where you will want to omit certain track.
