### ISSUE TITLE
Drive config for ASUS DRW-24D5MT

### ISSUE THREAD

**Issue by CookiePLMonster** [superg/redumper#63]
As discussed on the VGPC Discord, `ASUS DRW-24D5MT` is a "generic" ASUS that is not supported by Redump, but it proved good enough to refine a damaged dump, and it works with a sane set of settings: `read offset: +6, C2 shift: 0, pre-gap start: -135, read method: BE_CDDA, sector order: DATA_SUB_C2`.

Example log file:
[Matchbox_Demo_CD_Poland.log](https://github.com/superg/redumper/files/11972696/Matchbox_Demo_CD_Poland.log)

**Comment by superg** [comment]
Implemented
