### ISSUE TITLE
Log output - missing empty line between error count and PVD for multisession discs

### ISSUE THREAD

**Issue by mictlantecuhtle** [superg/redumper#64]
**Issue**
The redumper log for multisession discs does not create an empty line between the `REDUMP.ORG errors:` and `ISO9660 [Audio CD (Track 3).bin]:` lines of the log. Example as follows:

```
CD-ROM [Audio CD (Track 3).bin]:
  sectors count: 87627
  mode1 sectors: 87477
  invalid sync sectors: 150
  ECC errors: 1
  EDC errors: 1

  REDUMP.ORG errors: 1
ISO9660 [Audio CD (Track 3).bin]:
```

**Expected Behaviour**
There should be an empty line between these elements of the log. Example:

```
CD-ROM [DPCS0201.bin]:
  sectors count: 301514
  mode2 sectors: 301514
  mode2 (form 1) sectors: 301514

  REDUMP.ORG errors: 0

ISO9660 [DPCS0201.bin]:
```

I suspect this may be causing an issue where MPF cannot correctly grab error information from redumper logs for multisession discs.

[Audio CD.log](https://github.com/superg/redumper/files/12032599/Audio.CD.log)

**Comment by superg** [comment]
fixed.
