### ISSUE TITLE
Unable to refine CD dumps with recent builds

### ISSUE THREAD

**Issue by joshstoik1** [superg/redumper#68]
Hi there,

As mentioned in #66 , the `refine` action hasn't been working for me in recent builds. It just prints
```
*** REFINE


*** END
```
and quits.

The [attached log](https://github.com/superg/redumper/files/12076717/cdda.log) shows a standard `dump`, followed by `refine` requests from each Linux release going back to `176`, which worked the way it was supposed to. The `--refine-subchannel` flag was used to make sure there'd be something to refine on each pass, but the issue isn't subchannel-specific.

Another way to reproduce this (without bad data) is by skipping sectors on the first pass. [This log](https://github.com/superg/redumper/files/12076836/partial.log) shows an incomplete `dump` (courtesy of an `--lba-start` offset), followed by `refine` requests without the `--refine-subchannel` flag. Again, the missing data isn't picked up until build `176`.

If there is any other information I can provide to help you out, please let me know. Thanks!

**Comment by superg** [comment]
I'll check that out, will see if I can squeeze some time for this today, thanks for reporting

**Comment by superg** [comment]
Ah wait, you haven't used --retries option. 
I changed that behavior recently, if there is no --retries=X argument, refine exits.

This way it gives you more control if you want to skip refine even if errors for further analysis.

**Comment by joshstoik1** [comment]
Sorry @superg, I hadn't noticed that `--retries` became mandatory. That is exactly where I was going wrong. Thank you!
