### ISSUE TITLE
PS3

### ISSUE THREAD

**Issue by superg** [superg/redumper#93]
pull internal serial from PS3_DISC.SFB. If it doesn't exist, use "PS3_GAME/PARAM.SFO" as a primary source.

**Comment by Deterous** [comment]
PS3_DISC.SFB *should* always exist, it is more important thatn PS3_GAME/PARAM.SFO
If it reverts to using PARAM.SFO, please add a hyphen in the middle: "BLES01234" -> "BLES-01234"

**Comment by Ragowit** [comment]
I'm somewhat against modifying data. IF it reverts to using PARAM.SFO, do NOT add a hyphen. Instead maybe a mention that the data was found in .SFO (maybe full path to the .SFO in-case of several .SFO's?) instead of the .SFB.
